#!/bin/sh
# Set values from arguments
while getopts ":d:u:g:m" opt; do    
  case $opt in
    d)
        DST=$OPTARG
        ;;
    u)
        USER=$OPTARG
        ;;
    g)
        GROUP=$OPTARG
        ;;
    m)
        MODE=$OPTARG
        ;;
    *)
        echo "  ! Unknown parameter \"$PARAM\""
        exit 1
        ;;
  esac
done
shift $((OPTIND -1))

# Set defaults
[ -z $DST ] && echo "  ! Missing directory" && exit 1
[ -z $USER ] && USER="root"
[ -z $GROUP ] && GROUP="root"
[ -z $MODE ] && MODE="640"

if [ -d $DST ]; then
  exit 0
else
  mkdir -p ${DST}
  RET=$?
  chown ${USER}:${GROUP} ${DST}
  RET1=$?
  chmod ${MODE} ${DST}
  RET2=$?
  if [ $RET -gt 0 -o $RET1 -gt 0 -o $RET2 -gt 0 ]; then
    exit 1
  fi
fi
