#!/bin/sh
# Set values from arguments
while getopts ":d:u:g:m" opt; do
  case $opt in
    d)
        DST=$OPTARG
        ;;
    u)
        USER=$OPTARG
        ;;
    g)
        GROUP=$OPTARG
        ;;
    m)
        MODE=$OPTARG
        ;;
    *)
        echo "  ! Unknown parameter \"$PARAM\""
        exit 1
        ;;
  esac
done
shift $((OPTIND -1))

# Set defaults
[ -z $DST ] && echo "  ! Missing directory" && exit 1
[ -z $USER ] && USER="root"
[ -z $GROUP ] && GROUP="root"
[ -z $MODE ] && MODE="750"

echo "  * ${DST}"
if [ -d ${DST} ]; then
  echo "    = Destination directory exists"

  # Retrieve user/group/mode from the file if it exists and we need to update rights/mode
  FSTAT=`stat -c %a-%U-%G ${DST}`
  FMODE=`echo ${FSTAT} | cut -f 1 -d '-'`
  FUSER=`echo ${FSTAT} | cut -f 2 -d '-'`
  FGROUP=`echo ${FSTAT} | cut -f 3 -d '-'`

  if [ $FUSER != $USER ] || [ $FGROUP != $GROUP ]; then
    echo "    => Fixing user/group"
    chown ${USER}:${GROUP} ${DST} || exit 1
  fi
  if [ $FMODE != $MODE ]; then
    echo "    => Fixing mode"
    chmod ${MODE} ${DST} || exit 1
  fi

  exit 0
else
  # Create directory as configured
  echo "    => Creating directory"
  mkdir -p ${DST}
  RET=$?
  chown ${USER}:${GROUP} ${DST}
  RET1=$?
  chmod ${MODE} ${DST}
  RET2=$?
  if [ $RET -gt 0 ] || [ $RET1 -gt 0 ] || [ $RET2 -gt 0 ]; then
    exit 1
  fi
fi
