#!/bin/sh
# Set values from arguments
while getopts ":s:d:u:g:m" opt; do    
  case $opt in
    s)
        SRC=$OPTARG
        ;;
    d)
        DST=$OPTARG
        ;;
    u)
        USER=$OPTARG
        ;;
    g)
        GROUP=$OPTARG
        ;;
    m)
        MODE=$OPTARG
        ;;
    *)
        echo "  ! Unknown parameter \"$PARAM\""
        exit 1
        ;;
  esac
done
shift $((OPTIND -1))

# Set defaults
[ -z $SRC ] && echo "  ! Missing source file" && exit 1
[ -z $DST ] && echo "  ! Missing destination file" && exit 1
[ -z $USER ] && USER="root"
[ -z $GROUP ] && GROUP="root"
[ -z $MODE ] && MODE="640"

SRCSUM=`[ -f $SRC ] && sha1sum $SRC | cut -f 1 -d ' ' || echo "nosrc"`
DSTSUM=`[ -f $DST ] && sha1sum $DST | cut -f 1 -d ' ' || echo "nodst"`

if [ "${SRCSUM}" = "${DSTSUM}" ]; then
  echo "  ? Source and destination match"
  exit 0
else
  # Exit if we miss the source file
  if [ "${SRCSUM}" = "nosrc" ]; then
    echo "  ! Source file not found: ${SRC}"
    exit 1
  fi
  cp -f ${SRC} ${DST}
  RET=$?
  chown ${USER}:${GROUP} ${DST}
  RET1=$?
  chmod ${MODE} ${DST}
  RET2=$?
  if [ $RET -gt 0 -o $RET1 -gt 0 -o $RET2 -gt 0 ]; then
    exit 1
  fi
fi
