#!/bin/sh
# Set values from arguments
BACKUP=0
echo "STATEDIR = $STATEDIR"
while getopts "s:d:u:g:m:b" opt; do
  case $opt in
    s)
        SRC=$OPTARG
        ;;
    d)
        DST=$OPTARG
        ;;
    u)
        USER=$OPTARG
        ;;
    g)
        GROUP=$OPTARG
        ;;
    m)
        MODE=$OPTARG
        ;;
    b)
        BACKUP=1
        ;;
    *)
        echo "  ! Unknown parameter \"$PARAM\""
        exit 1
        ;;
  esac
done
shift $((OPTIND -1))

# Set defaults
[ -z $SRC ] && echo "  ! Missing source file" && exit 1
[ -z $DST ] && echo "  ! Missing destination file" && exit 1
[ -z $USER ] && USER="root"
[ -z $GROUP ] && GROUP="root"
[ -z $MODE ] && MODE="640"

SRCSUM=`[ -f $SRC ] && sha1sum $SRC | cut -f 1 -d ' ' || echo "nosrc"`
DSTSUM=`[ -f $DST ] && sha1sum $DST | cut -f 1 -d ' ' || echo "nodst"`

# Exit if we miss the source file
if [ "${SRCSUM}" = "nosrc" ]; then
  echo "  ! Source file not found: ${SRC}"
  exit 1
fi

echo "  * ${DST}"
if [ "${SRCSUM}" = "${DSTSUM}" ]; then
  echo "    = Source and destination match"

  # Retrieve user/group/mode from the file if it exists and we need to update rights/mode
  FSTAT=`stat -c %a-%U-%G ${DST}`
  FMODE=`echo ${FSTAT} | cut -f 1 -d '-'`
  FUSER=`echo ${FSTAT} | cut -f 2 -d '-'`
  FGROUP=`echo ${FSTAT} | cut -f 3 -d '-'`

  [ $FUSER != $USER -o $FGROUP != $GROUP ] && \
    echo "    => Fixing user/group" && \
    (chown ${USER}:${GROUP} ${DST} || exit 1)
  [ $FMODE != $MODE ] && \
    echo "    => Fixing mode" && \
    (chmod ${MODE} ${DST} || exit 1)

  exit 0
else
  # Copy the file over destination and set configured rights
  [ $BACKUP -eq 1 -a -f ${DST} ] && cp -f ${DST} ${DST}.shmgmt.bkp
  echo "    => Copy destination over"
  cp -f ${SRC} ${DST}
  RET=$?
  chown ${USER}:${GROUP} ${DST}
  RET1=$?
  chmod ${MODE} ${DST}
  RET2=$?
  if [ $RET -gt 0 -o $RET1 -gt 0 -o $RET2 -gt 0 ]; then
    exit 1
  fi
fi
