#!/bin/sh
# Simple wrapper around xbps

_check_installed() {
  PACKAGE=$1
  xbps-query $PACKAGE > /dev/null 2>&1
  RET=$?
  if [ $RET -eq 0 ]; then
    echo "= Package is installed"
    return 0
  elif [ $RET -eq 2 ]; then
    echo "= Package is not installed"
    return 1
  else
    echo "  ! Error processing xbps-query ${PACKAGE}"
    exit 1
  fi
}

_install() {
  PACKAGE=$1
  IS_INSTALLED=`_check_installed ${PACKAGE}`
  RET=$?
  echo "    $IS_INSTALLED"
  if [ $RET -ne 0 ]; then
    echo "    => Installing package"
    xbps-install -Sy ${PACKAGE} > /dev/null 2>&1
    RET=$?
    if [ $RET -ne 0 ]; then
      echo "  ! Error processing xbps-install -Sy ${PACKAGE}"
      exit 1
    fi
  else
    return 0
  fi
}

_remove() {
  PACKAGE=$1
  IS_INSTALLED=`_check_installed ${PACKAGE}`
  RET=$?
  echo "    $IS_INSTALLED"
  if [ $RET -eq 0 ]; then
    echo "    => Removing package"
    xbps-remove -Ry ${PACKAGE} > /dev/null 2>&1
    RET=$?
    if [ $RET -ne 0 ]; then
      echo "  ! Error processing xbps-remove -Ry ${PACKAGE}"
      exit 1
    fi
  else
    return 0
  fi
}

# Check that a package name has been given
if [ -z $2 ]; then
  echo "  ! You must provide a package name"
  exit 1
fi

echo "  * $2 package"

# Check if an action has been set
case $1 in
  install)    _install $2;;
  remove)     _remove $2;;
  *)        echo "  ! Invalid action - (install|remove)"
            exit 1
            ;;
esac
