#!/bin/sh
set -e

# First deploy file but ensure directory is present
$SHELL ${TMPDIR}/modules/dir -d /etc/iptables
$SHELL ${TMPDIR}/modules/file -s ${TMPDIR}/files/etc/iptables/iptables.rules \
                              -d /etc/iptables/iptables.rules

# Then if successful restart service
$SHELL ${TMPDIR}/modules/${DIST}_service -e restart iptables
